# Generated by Django 6.0.7 on 2026-08-07 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Income', 'Income')], default='Budget', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.budget'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'category_type', 'owner'), name='unique_category_per_owner'),
        ),
    ]
